"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("poper");
var $ = require("jquery");
require("bootstrap");
require("bootstrap/dist/css/bootstrap.min.css");
require("font-awesome/css/font-awesome.css");
var manage = require("./Manage");
var tests = require("./Tests");
window["Manage"] = manage;
window["tests"] = tests;
window["$"] = $;
